// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyCrhFZ46m2WHdFvAlr2BWpybadi-uUfk',
    appId: '1:314217327347:web:1f72298fb2e1ed55a9a586',
    messagingSenderId: '314217327347',
    projectId: 'market-wars',
    authDomain: 'market-wars.firebaseapp.com',
    storageBucket: 'market-wars.firebasestorage.app',
    measurementId: 'G-EDV371WJP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsx2dDnYGwHFDxTvsQG6IO0LYUtelA5EQ',
    appId: '1:314217327347:android:893043a88f88c339a9a586',
    messagingSenderId: '314217327347',
    projectId: 'market-wars',
    storageBucket: 'market-wars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVwVhOebnGpIag7X0IUH0srBhbLE026eA',
    appId: '1:314217327347:ios:d9ff2eb9bdbf60c9a9a586',
    messagingSenderId: '314217327347',
    projectId: 'market-wars',
    storageBucket: 'market-wars.firebasestorage.app',
    iosBundleId: 'com.example.marketwars',
  );
}
